### ISSUE TITLE
question about installation

### ISSUE THREAD

**Issue by diomed** [Ranks/emojione#110]
hi, sorry for this but I'd like to ask a question about installation.
I'm not really sure, is there a way to install this on my website 
without having to have all images hosted on it.

I would prefer if this could be feasible so I'd include js+css from cdn
and it would pull images from emojione library at cdn
https://cdnjs.com/libraries/emojione

and display them on site.

what else is needed if I want to include this in a web forum, through bbc?

**Comment by mikebe11** [comment]
Including the library via CDN is quite easy. We have some instructions on our site, on this page.
http://emojione.com/developers
Out of the box it serves PNG images from this CDN - https://cdn.jsdelivr.net/emojione/assets/png/
If you prefer cdnjs.com you would need to replace this line in emojione.js

ns.imagePathPNG = '//cdn.jsdelivr.net/emojione/assets/png/';

with this

ns.imagePathPNG = '//cdnjs.cloudflare.com/ajax/libs/emojione/1.4.1/assets/png/';

and include a link to this revised JS file in your html instead of the one from the CDN.

Here you can find other examples/demos on how to incorporate this library into your site. 
http://git.emojione.com/demos/index.html
We are in the process of updating the PHP examples to reflect the recent change but the JS library examples are current.
