### ISSUE TITLE
toShort Performance Improvement

### ISSUE THREAD

**Issue by hsjgrobler** [Ranks/emojione#117]
Hey, I see in the JS source there is comment indicating that the toShort function "needs to be improved into one big replacement instead, for performance reasons". Is there any ETA on this? I ask because I am using emojione to transform unicode to shorts on a lot of strings and it taking longer than I hoped it would.

Are there any other tips for performance? Would it speed things up if I ran the strings through a regex to find chars outside of the normal range and then pass those to the function instead of passing the entire string? I'm trying to figure out where the bottleneck is happening. Is it at the lookup of the rather large array that maps the unicode to shorts?

Thanks in advance.

I'm using the node lib at the moment.

**Comment by IndomitableIrk** [comment]
I looked at the source some more and if i understand correctly it looping through entire emojioneList and the replacing any occurrences of that unicode in the string. Wouldn't it be faster to do a reverse lookup by looping through the passed string and looking up the shortcode for that string? You would likely need another map that has the unicode as the key and shortcode as the value. However I suspect the way surrogate pairs are handled makes this harder?

**Comment by ck-on** [comment]
Considering many users are on mobile and don't have the javascript power, rendering it server-side made far more sense to me.

I came up with a complex regex to match all 1262 (and only the 1262) codes in binary rather than  surrogate pairs, etc. so it can be done directly against mysql utf8mb4 text. The overhead server-side is trivial, even on a very large/active forum via php hhvm.

I may share the regex if there is any interest, it was a lot of work since there isn't machine automation yet to create regex like that, though I am working on some code to automate writing the regex.

**Comment by mikebe11** [comment]
closing this based on commit a5317fdb5aaa0cc4eaed76e0975149b27d494ac6 for #53
