### ISSUE TITLE
One face renders smaller than all other faces 1F61B 😛

### ISSUE THREAD

**Issue by ck-on** [Ranks/emojione#123]
U+1F61B  😛  FACE WITH STUCK-OUT TONGUE 	

Should look just like this but with both eyes open

U+1F61C 😜 FACE WITH STUCK-OUT TONGUE AND WINKING EYE 

However 1F61B is rendered smaller in circle than all other faces.

![1f600](https://cloud.githubusercontent.com/assets/3338142/9043914/10a2e0b4-39e7-11e5-86c4-9a15ad223524.png) ![1f61b](https://cloud.githubusercontent.com/assets/3338142/9043888/d586c5ae-39e6-11e5-8d2e-33a3663ab8e5.png) ![1f61c](https://cloud.githubusercontent.com/assets/3338142/9043890/d76e75a6-39e6-11e5-8f8f-0bd13ac35fbf.png)

Search for `tongue` on http://emoji.codes/?q=tongue and zoom in to compare sizes.

**Comment by mikebe11** [comment]
You're right, the diameter of face with stuck out tongue is a little smaller than the others. The emoji are designed on a square canvas. Smileys' diameters are pretty close to the canvas size so there isn't much extra room. Because FWSOT was designed with the tongue extended a little outside the circle that emoji's height was larger than it's width. The whole thing was scaled to fit and that smiley's diameter ended up a little smaller than the rest.
Since we don't have plans to update this collection I'll pass this note on to the designers of the new one. It's a good detail to watch for while creating new smileys. Thanks

**Comment by ck-on** [comment]
@mikebe11 for our planning, what is the general timetable for the new collection? 

Are we talking weeks or more likely months? October?

**Comment by mikebe11** [comment]
@ck-on  Right now we figure around the end of the year, so I would say more like October - December.
