### ISSUE TITLE
Missing Regional Indicator support

### ISSUE THREAD

**Issue by AshleyWright** [Ranks/emojione#134]
The project is currently missing support for the country codes:
AQ, AS, AX, BL, BQ, BV, CC, CK, CW, CX, GF, GG, GP, GS, HM, IM, IO, MF, MP, MQ, NF, PM, PN, RE, SJ, SS, SX, TC, TF, TK, UM, VG, YT

To reproduce, here they are formatted as shortcodes.
```
:aq::as::ax::bl::bq::bv::cc::ck::cw::cx::gf::gg::gp::gs::hm::im::io::mf::mp::mq::nf::pm::pn::re::sj::ss::sx::tc::tf::tk::um::vg::yt:
```

Source: http://esham.io/2015/04/emoji-flags-redux

**Comment by rodrigopolo** [comment]
I believe their are going to add those in their 2016 collection which has been announced to be released on November, I know which emojis are missing because I have created a list of all of them using the latest Apple emojis from OS X and the official Unicode 8.0 list:

http://rodrigopolo.com/files/emojilist

I also have created a little library for emoji replacement BUT I'm waiting for Emoji One 2016 collection in order to include the SVG edition:

https://github.com/rodrigopolo/minEmoji

**Comment by mikebe11** [comment]
@AshleyWright  Our plan is to offer the current set of flags and add those that we don't have in this list: http://emojipedia.org/flags/
This will cover many of those you mentioned. The new flags will be available in the new set. We aren't developing any more assets for the current one.

**Comment by robin0van0der0v** [comment]
This issue can probably be closed, all flags listed in the post are currently supported now.

**Comment by mikebe11** [comment]
@robin0van0der0v  Thank you for the reminder. Yes, our flag collection has been updated with v2 so this issue will be closed.
