### ISSUE TITLE
Title attribute for emoji images

### ISSUE THREAD

**Issue by bmironov** [Ranks/emojione#140]
Hello,

Thanks a lot for great library of standard emoticons.

This is not an issue, but more of "feature request" it would be great to have at least option to set title attribute for emoji images. I think I'm not the only person in the world who didn't memorize all possible icons, hence it would help if just by hovering cursor over icon browser will show its meaning via title attribute.

Thanks a lot again,
Boris

**Comment by mikebe11** [comment]
@bmironov Thank you Boris. That's a good suggestion. Perhaps it's worth implementing at some point. Or even adding a title flag to be able to add them or not if for some reason there's a performance issue or distraction with them.

**Comment by cygery** [comment]
Hi,
I've originally added the title attribute to a fork and created Ranks/emojione#155 for this original repo accordingly. This implementation uses no flag, though, but includes the title attribute always.

**Comment by derekmooney** [comment]
I'd like to +1 this, but also ask for the ability to add an aria-label. I did a similar update to twemoji - we wanted our title popup to have both the emoji in unicode, and the short name, so users can discover the shortcut. We also added an aria-label so that screen readers would read through it nicely:

<img class="emoji" draggable="false" alt="👍" src="https://twemoji.maxcdn.com/svg/1f44d.svg" title="👍 - :thumbsup:" aria-label="👍: Thumbsup">

Since twemoji doesn't do anything with shortnames, I implemented it there with a callback function, which lets us translate the emoji descriptions, as well.

I'm considering switching our project to emojione (and looking forward to it), but this stuff would be a requirement for us due to accessibility requirements (I might just fork it for now, probably starting with cygery's fork, but I'm certainly not any more likely to update the php than cygery is).

**Comment by gdpelican** [comment]
@derekmooney any progress on this? We're using emojione on my project and have had a wave of requests for the title attribute (and aria-label wouldn't hurt as well)

I, like the others, am happy to implement in JS, but less likely to touch PHP. Would you accept a js-only solution if it were configurable and tested, @mikebe11 ?

**Comment by mikebe11** [comment]
@gdpelican Sure. Was waiting on some time to manage both together but can't tell when that time might come. Feel free to submit a PR and we will look it over. I will request there be a boolean option to display or not. Another note, don't just depend on the tests included in this repo. They're a work in progress and don't include full coverage.

**Comment by derekmooney** [comment]
The more I looked at incorporating emojione directly, there were simply too many customizations we needed, for the data sets and for the replacement approaches, that I ended up writing some grunt tasks to adapt the json data from this repo for use with our own angular filters. After applying our overwrites to the emoji data, I'm essentially building out optimized maps and regular expressions for the replacement, and replacing with specifically the tags I need.

Even if you didn't want to go that far, it wouldn't be hard to use the regUnicode from the library directly, and write your own replacement function. But it'd be relying on internals to the library that could very likely change.

**Comment by caseyahenson** [comment]
Hi all, I would encourage you to have a look at the new implementation for JS and PHP which sets the title attribute on by default (no aria-label yet), and allows for the feature to be turned off. I'll be drafting this into a release soon, feedback encouraged.
