### ISSUE TITLE
Get list of emojis by category

### ISSUE THREAD

**Issue by koas** [Ranks/emojione#149]
In our site we pop a box for our users to click on the emoji they want. We have five tabs (people, nature, food & celebration, travel & places and objects & symbols) which we populate "by hand" in our code.

It would be great to be able to call a function in the emojione JS library to list all the shortcodes of the emojis of each category. Right now with every new release of emojione we have to rebuild our emoji list for each category tab.

**Comment by koas** [comment]
I just found the emoji.json file, which contains the category for all emojis, so we can use this file to generate our tab code.

Still, I think it would be useful to be able to list from JS the emojis of each category, that would save some work when upgrading.

**Comment by mikebe11** [comment]
Yes, we provide that file for any custom work that developers may need to do. I don't see a specialized function like that being added. It forces our structure on users which they may not want plus it requires us to add categories into the file to keep it contained to one component.

If you're working with a local copy instead of the CDN you can add your function in the form of `ns.categoryList = function() { ... }` and call it as `emojione.categoryList()`.

**Comment by koas** [comment]
I'll do that, thanks for your reply and the great work you're doing!
