### ISSUE TITLE
Missing Comet emoji

### ISSUE THREAD

**Issue by legurnster** [Ranks/emojione#157]
I don't know if it's just me but I can't find the Comet emoji as part of Unicode 1 (1993 - see here: http://emojipedia.org/comet/)

By the way, lovely emojis. I'm integrating them into a new social network at the moment. Thanks for releasing them.

**Comment by legurnster** [comment]
I've just read on that very link it's only just been

**Comment by legurnster** [comment]
Sorry for reopening then closing etc. Just read on that very link it's just been brought into iOS9 but can you close this when it's in EmojiOne?

**Comment by mikebe11** [comment]
Hi,

The current set you're working with is no longer in development. We won't be adding the comet to it. There are many more that were recently released that are also not currently available. We're finalizing a whole new collection that will be available next week. You can see samples of it on our social media pages. 
https://www.instagram.com/emojione/ 
The new set will include the latest Unicode 8 emoji, iOS 9.1 (including the comet) and diversity emoji.

I'm gonna close this issue since we aren't working more on the current art. There are many more new ones not currently available. We don't want to encourage more issues regarding these. The comet and others you may be wanting to use will be available soon.

Thank you.
