### ISSUE TITLE
Emoji Shortname not converting

### ISSUE THREAD

**Issue by defraz** [Ranks/emojione#158]
While adding Emojione to our app we discovered a number of emoji shortnames that do not convert in Javascript .toImage(str) or .shortnameToImage(str) but convert in their PHP equivalents. 

Here is a list of non-working shortnames that we've discovered:

```
:house-abandoned:
:airplane_northeast:
:jet_up:
:airplane_small_up:
:airplane_up:
:fire_engine_oncoming:
:train_diesel:
:ballot_box_x:
:ballot_x:
:ballot_box_check:
:light_check_mark:
:rosette_black:
:mood_lightning:
:info:
:triangle_round:
:clockwise_arrows:
:cancellation_x:
:girls_symbol:
:boys_symbol:
:piracy:
:prohibited:
:mood_bubble_lightning:
:mood_bubble:
:anger_left:
:thought_right:
:thought_left:
:speech_three:
:speech_two:
:speech_right:
:speech_left:
:celtic_cross:
:cross_white:
:descending_notes:
:ascending_notes:
:ringing_bell:
:bullhorn_waves:
:bullhorn:
:right_speaker_three:
:right_speaker_one:
:right_speaker:
:pencil3:
:folder_open:
:folder:
:pennant_black:
:pennant_white:
:pushpin_black:
:book2:
:frame_tiles:
:frame_x:
:stock_chart:
:notepad-spiral:
:notepad:
:note:
:notepad_empty:
:note_empty:
:pages:
:page:
:document_text:
:document:
:envelope_stamped_pen:
:envelope_flying:
:envelope_stamped:
:envelope_back:
:crossbones:
:optical_disk:
:hard_disk:
:cartridge:
:floppy_white:
:floppy_black:
:flip_phone:
:telephone_black:
:telephone_white:
:left_receiver:
:stereo:
:keyboard_with_jacks:
:calculator:
:desktop_window:
:network:
:keyboard_mouse:
:mouse-one:
:computer_old:
:heart_tip:
:bouquet2:
:finger_pointing_down2:
:finger_pointing_up:
:finger_pointing_right:
:finger_pointing_left:
:finger_pointing_down:
:hand_victory:
:thumbs_down_reverse:
:thumbs_up_reverse:
:hand_splayed_reverse:
:turned_ok_hand:
```

As you can see the list is not exactly insignificant. This only appears to be an issue with the Javascript implementation as the PHP library will render these.

**Comment by mikebe11** [comment]
You should update your copy of the library. The two "official" shortnames in that list are incorrect, :house-abandoned: and :notepad-spiral:  These have underscores instead of dashes in the current code, :house_abandoned: and :notepad_spiral:
Regarding the others, we initially released V7 with the full set of Unicode 7 emoji. Afterwards they amended their standard set, removing the others in your list. Since that time we've removed most code references to those. Some remain, like the PHP references. The art is still in here as well. These are not "official" emoji in the collection. Consider them "easter eggs" to be used as you see fit. All references to those will be removed in the next major release.

**Comment by defraz** [comment]
Not sure you quite caught the gist of the posted issue. If I go around the two functions in Javascript and just use the provided unicode characters in the .json file then they all work and render out correctly.

This appears to be an issue in the Regex for the library not correctly matching shortnames as I should be able to provide a completely custom version of the list with different shortnames and as long as the unicode is correct it should match and render out the corresponding emoji.

Also emoji working in only part of the library doesn't exactly fit the definition of 'easter egg' it does fit the definition of broken though.
