### ISSUE TITLE
emoji.json and ns.emojioneList in emojione.js are not consistent

### ISSUE THREAD

**Issue by kylemeier** [Ranks/emojione#161]
Somewhere between 1.5.0 and 1.5.2 a decent amount of emojis disappeared from ns.emojioneList (found in emojione.js) that are still in emoji.json. I'm using emoji.json to build an emoticon tray so these emojis can still be selected in the tray, but when I go to convert them to unicode, emojione.js doesn't find them. I'm converting to unicode before sending to our backend to keep things consistent with the mobile versions of the app I'm building. Without the conversion, the shortname is saved instead of something the mobile apps can use.

Not sure of everything removed, but I know all emojis containing '_reverse' were removed.

Should I be able to trust that these lists are kept consistent with each other? Or am I misunderstanding the point of these lists?

Edit: Looks like this is the same issue causing #158

**Comment by mikebe11** [comment]
They are not currently consistent with each other. Turns out developers are using the json files in different ways and much more than was expected. Here is a list of the unicode values that you can exclude from your project. They won't be included in any future file updates.

1F394, 1F395, 1F398, 1F39C, 1F39D, 1F3F1, 1F3F2, 1F3F6, 1F4FE, 1F546, 1F547, 1F548, 1F568, 1F569, 1F56A, 1F56B, 1F56C, 1F56D, 1F56E, 1F571, 1F572, 1F57B, 1F57E, 1F57F, 1F581, 1F582, 1F583, 1F585, 1F586, 1F588, 1F589, 1F58E, 1F58F, 1F591, 1F592, 1F593, 1F594, 1F597, 1F598, 1F599, 1F59E, 1F59F, 1F5A6, 1F5A7, 1F5A9, 1F5AA, 1F5AB, 1F5AD, 1F5AE, 1F5AF, 1F5B3, 1F5B4, 1F5B8, 1F5B9, 1F5BD, 1F5BE, 1F5C0, 1F5C1, 1F5C6, 1F5C7, 1F5C9, 1F5CA, 1F5CE, 1F5CF, 1F5D0, 1F5D4, 1F5D8, 1F5D9, 1F5E0, 1F5E2, 1F5E8, 1F5E9, 1F5EA, 1F5EB, 1F5EC, 1F5ED, 1F5EE, 1F5F0, 1F5F1, 1F5F2, 1F5F4, 1F5F5, 1F5F8, 1F5F9, 1F6C6, 1F6C7, 1F6C8, 1F6C9, 1F6CA, 1F6E6, 1F6E7, 1F6E8, 1F6EA, 1F6F1, 1F6F2

**Comment by timshannon** [comment]
I just noticed with the 2.0 release that the case isn't consistent now either.

For instance, it looks like emoji.json refers to lower case images names while ns.emojioneList are upper case:

Look at 1F637 vs 1f637  

Or is that intentional?  Right now I'm using the json data to map to images and using the asumption that unicode == image name

**Comment by timshannon** [comment]
Hm, It also doesn't appear to be consistently uppercase.  see 1f917

**Comment by ping** [comment]
Possibly related #163 

This upper/lower case inconsistency peppered throughout the v2 release has made this new release completely unusable. Even the demos are broken due to bad png/svg paths (lower/upper case differences in file names).

Examples:
v2 https://cdn.rawgit.com/Ranks/emojione/v2.0.0/demos/ascii-smileys.html (broken)
v1.5 https://cdn.rawgit.com/Ranks/emojione/v1.5.2/demos/ascii-smileys.html

v2 https://cdn.rawgit.com/Ranks/emojione/v2.0.0/demos/jstoimage.html (broken)
v1.5 https://cdn.rawgit.com/Ranks/emojione/v1.5.2/demos/jstoimage.html

**Comment by mikebe11** [comment]
@timshannon Apologies, but in the rush of release we unfortunately were unable to take the care in updating that we would have liked. The filenames have been normalized. They should be lowercase in the json files and in ns.emojioneList. Are you still seeing a unicode point that is uppercase? The ones you mentioned, 1f917 and 1f637 appear to be fine now.

**Comment by timshannon** [comment]
@mikebe11 Yep, the entire list looks to be good to me now.  I'm not seeing any errors.

Thanks,

**Comment by mikebe11** [comment]
:+1:
