### ISSUE TITLE
how about a webfont OR why are fonts device specific?

### ISSUE THREAD

**Issue by tobibeer** [Ranks/emojione#189]
I'd like to use these emojis in a web-context but I'm a bit baffled they'd be targeted at this or that device.

Will there have to be a dedicated webfont to use emojione in a comparable manner to fontawesome?

**Comment by tobibeer** [comment]
I just looked at the file-sizes of the existing tffs and realized they possibly are unsuitably large.

**Comment by mikebe11** [comment]
For web-context our PNG or SVG offerings are all that we have at the moment. That use is generally as an image and not like Font Awesome.
Our fonts were generously provided by users who have experience in developing them. They're device specific mostly because those who developed them were primarily interested in changing the default emoji on their devices. If someone developed a webfont with our emoji we would offer it as well but that hasn't happened and we don't have the knowledge of fonts to do so ourselves.

**Comment by tobibeer** [comment]
Hi @mikebe11, thanks for the response, I think I'm closing this because I now think it's not worth the hassle.

I was unaware of how the emojis we see in devices are actually a unicode standard that is implemented in various ways across different environments. And so they are very much a different thing compared to webfonts, in that they extend on that standard while providing a different visual.

As for my purposes, all I really need is to use the emojis already given via unicode regardless of how different devices may present them. The key is being able to use such visual cues, even if certain environments or implementations such as emojione may present them better than others.
