### ISSUE TITLE
Odd choice of keywords on "pray" and "raised_hand"

### ISSUE THREAD

**Issue by salty-horse** [Ranks/emojione#197]
The "pray" character (U+1F64F PERSON WITH FOLDED HANDS) has the keywords "highfive" and "high five".

I'm not sure how that association was made.

A different emoji is a better candidate for the "high[ _]five" keywords:
>"raised_hand" U+270B RAISED HAND

(Not sure why that one has the keywords "female", "girl", "woman")

**Comment by mikebe11** [comment]
For some 1f64f is used to represent a high five, two raised hands in the air in a high five.
The "female", "girl", "woman" in 270b must have been added by mistake. Those obviously don't fit there.

**Comment by salty-horse** [comment]
Are you sure about U+1F64F sometimes represented as hands raised in the air? Because that sounds like U+1F64C PERSON RAISING BOTH HANDS IN CELEBRATION

**Comment by eosrei** [comment]
Since emoji started in Japan this character was originally "sorrow" or "bowing". It just happens to work well for "praying"  also in western countries.

```
PERSON WITH FOLDED HANDS
• can indicate sorrow or regret
• can also indicate pleading, praying, bowing, or
thanking
```
src: http://unicode.org/charts/PDF/U1F600.pdf

As for "highfive":
> The Apple version emoji, which does not show a person but just two hands, can be misinterpreted as meaning high five. 

src: http://www.iemoji.com/view/emoji/70/people/person-with-folded-hands

Many Apple emoji users believe this to be a high five and use it as such. So, EmojiOne needs to include that usage.

**Comment by mikebe11** [comment]
Closing this out. The inappropriate keywords for 270b have been removed.
