### ISSUE TITLE
"NO ONE UNDER 18" emoji is illogical compared to other symbols.

### ISSUE THREAD

**Issue by Swissnetizen** [Ranks/emojione#235]
Concerning 🔞 (<img src="https://s.w.org/images/core/emoji/16x16/1f51e.png" alt="🔞" class="emoji" draggable="false">) I think it is very problematic that the symbol doesn't correspond to other commonly used symbols which display a number and aim to give a meaning to it. 

Consider Figure 1, it is the international *maximum* speed limit sign; it uses *red* to denote maximum. Consider Figure 3, it is the international *minimum* speed limit sign; it uses *blue* to denote minimum. [Many more examples of this color scheme can be seen on the Wikipedia page comparing European road signs](https://en.wikipedia.org/wiki/Comparison_of_European_road_signs)

In addition as seen with Figures 2 and 4, red and blue are used for prohibition and requirements respectively. We should aim to match the usage of such popular signs.

I have 5 proposals to remedy the situation. The first takes is almost identical to the minimum speed limit sign. 2 and 3 add an additional symbol to help users who live in areas which do not use the international road signs (e.g. US, CA, AU) and take the style of Figure 4. 

Proposals 4 and 5 take the original style and add an additional symbol to make it more logical (somewhat like Figure 2).

![exp](https://cloud.githubusercontent.com/assets/2052887/14405036/5e63ab68-fe85-11e5-9600-9b39be88a35b.png)

**Comment by mikebe11** [comment]
@Swissnetizen We appreciate the well thought out proposal but we won't be changing this emoji. It's not that you don't make points worth considering but the changes deviate too far from the standard that we follow. When possible, we try to inject our own style into the look of an emoji but the current implementation is in line with the general offerings out there and more importantly, Unicode's offering. Your proposal might be better served in the hands of the Unicode Consortium since they manage the general standard for emoji.

**Comment by ShaunDreclin** [comment]
Just want to say I totally agree with you, and please do take it up with the Unicode Consortium. The emoji really doesn't make sense! It reads as "No 18" to me.
