### ISSUE TITLE
Emoji One Font

### ISSUE THREAD

**Issue by vicc** [Ranks/emojione#26]
First off this is awesome! I think these emoji's are 100x better. As an iOS developer, I do have a question with regards to installation. What would be the recommended way to get these working in a native app? Is there a font file that we can download (similar to how Symbola allows visibility for the new unicode 7.0 emoji through a .TFF file)? Again thanks for such an awesome project!

**Comment by wp9015362** [comment]
@kevinranks :

Could you please reopen this issue?

The Android OS supports colored Emojis natively via TTF fonts since version 4.4 KitKat.

And since 4.4 KitKat, stock Android by default comes with the Google "Noto Color Emoji" Emoji set in the form of the NotoColorEmoji.ttf font.

The native system Emojis therefore can be replaced with other Emojis by replacing this font with another font which includes different Emojis.

Unfortunately replacing this font still requires rooting the device.

There is an open issue on the AOSP issue tracker which addresses this issue, see:

https://code.google.com/p/android/issues/detail?id=69755

Anyway, there even is a third-party app called "Emoji Switcher" which allows to replace the font (also requires root), see:

http://forum.xda-developers.com/showthread.php?t=2722892

And someone on the XDA Developers forum apparently actually even managed to create a compatible font for the Emoji One Emoji set, see the following post:

http://forum.xda-developers.com/showpost.php?p=58610497&postcount=94

Here's a picture of what it looks like on an Android keyboard:

http://i.imgur.com/a2bj6Eo.png ([Source](http://forum.xda-developers.com/showpost.php?p=58610497&postcount=94))

![Image](http://i.imgur.com/a2bj6Eo.png)

So, as you can see, it is possible.

So, I don't think this issue should be closed.

It would be nice if such an Android font could officially be included in the Emoji One GitHub repository.

I also submitted a feature request on the CyanogenMod issue tracker and asked them if they could replace the Google "Noto Color Emoji" Emoji set with the "Emoji One" Emoji set or with the Twitter "Twemoji" Emoji set so that CyanogenMod users would get one of those Emoji sets by default, see:

https://jira.cyanogenmod.org/browse/CYAN-6486

Of course I can not speak for them and they do not have replied yet, but it would probably make their life easier if there would be a place where they simply could grab an official Emoji One Android system font from.

So, it would be really nice if Emoji One would offer an official Android Emoji system font.

Regards

**Comment by wp9015362** [comment]
PS:

I also found the following two links inside [that XDA Developers forum thread](http://forum.xda-developers.com/showthread.php?t=2722892):

https://code.google.com/p/color-emoji/

and:

http://typophile.com/node/103268

Maybe those would help to create the fonts?

Regards

**Comment by wp9015362** [comment]
As already mentioned in https://github.com/Ranks/emojione/issues/105 :

Looks like Google is working on it, see:

https://github.com/googlei18n/noto-emoji/issues/9

:wink:

Regards

**Comment by lalomartins** [comment]
It's not even just for Android, support for colour font is gradually spreading through all platforms. I don't think this is urgent, but I'd leave it open and revisit it early next year or so.

**Comment by jevtheboss** [comment]
There is a font file here http://forum.xda-developers.com/android/themes/font-twitter-emojione-emoji-replacements-t3020653 or here http://forum.xda-developers.com/razr-i/themes-apps/custom-emojis-android-t3235402
