### ISSUE TITLE
Android ttf?

### ISSUE THREAD

**Issue by vooze** [Ranks/emojione#264]
Hi

I really love emoji one (it's the perfect balance between stock Android and Apple, with a twist of flat. 

I'm using them on both my Android phone and chrome on both Linux and Windows. Seeing the new spring release is awesome. But now I have two different sets :( When will these be updated? https://github.com/Ranks/emojione/tree/master/assets/fonts

Thank you again!

**Comment by miguelsousa** [comment]
@vooze I plan to update the Android font soon after the new artwork fixes are done

**Comment by vooze** [comment]
@miguelsousa Thank you for the fast reply!

I'm looking forward it to it. Thank you again.

**Comment by caseyahenson** [comment]
@miguelsousa We're excited for the new font, we've had lots of interest in the update. We released 2.2.1 yesterday to address improperly-formatted svg files and we'll have 2.2.2 coming out within a week or so that buttons up UC9 code points (and includes skintone modifiers). Anything else from the artwork that was missing or off?

**Comment by miguelsousa** [comment]
no, I think that's all, plus any other little things that other people may find. I mainly want to see things settled for a bit before investing time into building a new font.
