### ISSUE TITLE
new EmojiOne Keyboard icon has insufficient contrast with Chrome toolbar (Win10, default theme)

### ISSUE THREAD

**Issue by lewisje** [Ranks/emojione#308]
As you can see, the light grey Chrome toolbar background is too close in color to the white body of the unicorn, its grey shadow, and its pale blue horn; one good idea for continuing to use the unicorn icon is to put it on a background with sufficient contrast.
![emojioneunicornicon](https://cloud.githubusercontent.com/assets/4865237/16894807/a86ea3b4-4b30-11e6-8201-9f448d14f1b4.png)

I didn't find a repo for the EmojiOne Keyboard extension, so I'm putting the issue here.

**Comment by caseyahenson** [comment]
@lewisje Thank you for your input. We've heard mixed opinions on the contrast of the icon since its inception, but considering many Chrome users implement themes which are almost always darker than the default Chrome theme (which is even lighter now with Chrome 52) much of our feedback has been positive. We'll continue to consider this from all angles!

**Comment by lewisje** [comment]
I know I sound like an Adlai Stevenson voter from the 1950s when I say this, but I barely ever see people who use non-default Chrome themes, unlike Firefox (most Chrome installations I see are from Twitch streamers, and few are from designers or whatever else your target audience is); I thought the idea was stupid when I first saw Chrome themes, but I'll give them another look now.
