### ISSUE TITLE
Feedback on current and desired use of shortnames

### ISSUE THREAD

**Issue by caseyahenson** [Ranks/emojione#400]
We're looking to collect feedback from those using EmojiOne libraries within their applications, specifically those making use of `:shortnames:`. Our goal is to make shortnames as functional as possible, yet as close to Unicode specifications as possible. 

Do you feel the current shortnames are structured in a way that makes them easy for users to reference, and have you received user feedback on this? 

When updates are made to emoji titles (and shortnames are updated to match), would you find it practical to reference shortnames via a shortname_alt data point for a fallback, or to run a script to convert any stored shortnames to their updated version?

Any additional comments on shortnames is encouraged. Thanks!

**Comment by Crissov** [comment]
Shouldn’t this be a topic at https://github.com/Ranks/emoji-alpha-codes instead?

Skin tones (`tone 1`–`tone 5`) neither match Unicode / Fitzpatrick (`1-2`, `3`–`6`) nor common language.

**Comment by flide** [comment]
I think the short-names is not a good way to reference the emoji's. We should stick with the name that remains constant through out the life of the emoji and short-name should be added to keyword list as a way of searching for it.

The skin tone emoji's should not be part of the data, for example emoji.json, since there exists a modifier category already. Instead the emoji's which have the diversity for them should have a flag indicating as such so that the diversity emojis can be constructed with the help of emoji unicode + modifer unicode.
