### ISSUE TITLE
Store emoji as unicode or shortname?

### ISSUE THREAD

**Issue by anri-asaturov** [Ranks/emojione#401]
What are the pros and cons of storing emoji in messages of chat application as unicode or shortname?

**Comment by seavan** [comment]
we, at our company, also struggle with that question

**Comment by zippunov** [comment]
Same in our company

**Comment by derekmooney** [comment]
We transmit unicode, because we have mobile apps that do not use emojione (or any other translation layer) and rely on native mobile support for emoji. The unicode seems to be the proper abstraction, whereas the shortnames are a shortcut for a user to *insert* that abstraction.

Others feel differently, of course, because if a particular unicode point isn't supported, you can get a nice shortname description. So you really have to select what makes sense for your case.
