### ISSUE TITLE
Hacker Cat (Windows 10 ZWJ sequence)

### ISSUE THREAD

**Issue by KAMiKAZOW** [Ranks/emojione#417]
Not a standardized emoji but since Windows 10 has it, adopting it would increase compatibility (plus it's a super fun emoji): hacker cat. See http://emojipedia.org/hacker-cat/

**Comment by Fastidious** [comment]
I give this a thumbs down. The aim should be to add standard emoji, not simply invented ones. If developers start doing that, it is not emoji anymore, it is mayhem.

**Comment by Crissov** [comment]
@Fastidious Vendors are free to add any ligature emojis they want. They can copy others, e.g. Twemoji’s Jolly Roger flag. The recently adopted new process is, put in a nutshell, that ZWJ sequences shall be added to Unicode TR 51 only after they have been supported by a major or multiple minor vendors. This is a good change.

Vendors could and perhaps should also add ligatures for often used emoji sequences, e.g. 👉👌, even though they are usually lacking a ZWJ.

**Comment by Fastidious** [comment]
@Crissov I see, and understand what you are saying. Yet, I would rather stick to what everyone has (that's just me). What good will it do to me to be able to send a ligature emoji, when the recipient will not be able to see it? Worthless, no? Now, when ligatures become mainstream, supported by at least the major players.. sure!

**Comment by Crissov** [comment]
Rereading the policy proposal documents I was implicitly referring to, i.e. [L2/17-005](http://www.unicode.org/L2/L2017/17005-emoji-zwj-proc.pdf) and [16-320](http://www.unicode.org/L2/L2016/16320-emoji-zwj-seq-process.pdf), I may have remembered and presented the process incorrectly. It’s more about adding the option to *request a documented sequence* instead of a code-point to <http://unicode.org/emoji/selection.html>. 

Anyhow, prior art should still help the case and thus my point remains the same: We don’t have to leave it to Apple, Google, Microsoft and Twitter to introduce new sequences. [Emoji Request](http://emojirequest.com), for instance, shows a lot of possible emojis that could be represented by more or less obvious sequences of existing emojis. Some characters have been added to Unicode with an anticipation of them being used in sequences (especially with emoticon faces), e.g. the light bulb 💡 for an idea or the dash 💨, sweat 💦, anger 💢, dizzy 💫 and sparkle ✨ symbols.

**Comment by scakemyeranasshole** [comment]
Maybe this will overcome the magical thinking that safely prevented intellectual honesty arising over the shotgun emoji
