### ISSUE TITLE
Ruleset.php, Client.php = 500 Internal Server error

### ISSUE THREAD

**Issue by Jeanp12** [Ranks/emojione#427]
When I try running these two scripts separately I get a 500 Internal Server Error. Is there any reason why this would happen? I ran the other scripts separately and they work perfectly fine.
![500ise](https://cloud.githubusercontent.com/assets/5701309/22958115/eb202cce-f2fa-11e6-855d-ef2ce0cce7f7.JPG)

**Comment by caseyahenson** [comment]
@Jeanp12 can you open the response from Ruleset.php and see if it's returning a specific error message?

**Comment by Jeanp12** [comment]
![500ise1](https://cloud.githubusercontent.com/assets/5701309/22961622/8bf1a230-f315-11e6-8205-573f8509ac72.JPG)

**Comment by caseyahenson** [comment]
@Jeanp12 near the'Headers' tab, click the 'Response' tab and screen cap what shows up there. If it's blank let me know as well.

**Comment by Jeanp12** [comment]
@caseyahenson It's blank....does that mean the problem is on my side>

**Comment by caseyahenson** [comment]
@Jeanp12 with the PHP libraries they really should be run by requiring autoload first. Client.php and Ruleset.php both have dependencies that are included with autoload and that's why those scripts will fail when called individually. Just out of curiosity, are you running into issues with the autoload implementation that prompted the individual file load?
