### ISSUE TITLE
emojione.mapShortToUnicode() is too computively expensive, it needs Memoization or precalculation

### ISSUE THREAD

**Issue by nel** [Ranks/emojione#45]
In the javascript version

*emojione.mapShortToUnicode()* is slow and creates tons useless of instances at each run. This is actually executed at every single call to public conversion api from utf8 to image (= very often in a single page app or a big page).
It would benefits greatly from memoization, the only drawback is the current api to add manual emoticon does not provide easy hook to invalid this memoization (no setters).

I had to monkeypatch my version of emojione to preserve decent execution timing: 

    emojione._mapShortToUnicode = emojione.mapShortToUnicode;
    emojione.mapShortToUnicode = function() {
      if (!emojione.memMapShortToUnicode) {
        emojione.memMapShortToUnicode = emojione._mapShortToUnicode();
      }
      return emojione.memMapShortToUnicode;
    };

PS: Regexp could also be precalculated instead of being generated every single execution but gain are much less visible in normal situation.

**Comment by Coquevas** [comment]
Both `emojione.mapShortToUnicode()`and `emojione.toShort()` have a `for` loop inside a `for` loop. I'm working in a way faster solution. Current implementation is doing ~150 operations per second (jsperf test on my machine) and my approach is doing 18K-48K operations per second. Performance is 120-320 times faster. Previous solution was constant speed, iterating the emojis list. My solution is variable speed because it's a function of the number of emojis in the parsed text but, probably, you need a text with more than 1K emojis to get previous implementation performance.

I'll try to put everything together tomorrow and I'll do a pull request.

PS: @nel you said "current api to add manual emoticons" but I'm not sure what are you talking about.

**Comment by nel** [comment]
Good news, what I meant by "current api to add manual emoticons" is that the current api allow to implement his own emoticon (and thus change the mapping). When the mapping is changed the map calculated by #mapShortToUnicode need to be recomputed. In the current api the mapping is a js variable and there is no way to tell when a programmer decide to change it (to invalidate cache/memoization e.g.).

Otherwise there is no use to actually recompute it at all, computation at loading or even better memoization at first run are the best options (no need for a fast computation as this only has to occur once par page).

My 2 cents.

**Comment by Coquevas** [comment]
I didn't what to break the current usage with an init() call or slow down the first load with the computation so I did the computation and memoization in the first call to the methods. You can take a look to the pull request in #53

**Comment by mikebe11** [comment]
closing this based on commit a5317fdb5aaa0cc4eaed76e0975149b27d494ac6 for #53
