### ISSUE TITLE
where is :avacado: ?

### ISSUE THREAD

**Issue by mcfiredrill** [Ranks/emojione#456]
Are there plans to add this and some of the newer emojis? 🥑

**Comment by Crissov** [comment]
[![U+1F951 :avocado:](https://rawgit.com/Ranks/emojione/master/assets/svg/1f951.svg)](https://github.com/Ranks/emojione/blob/master/assets/svg/1f951.svg)

Just a typo on your side? It is spelled _av**o**cado_. Since it's code point is U+1F951, you can also use `&#x1F951;` (or its decimal [equivalent](http://www.fileformat.info/info/unicode/char/1F951/)) in HTML and related markup languages.

**Comment by mcfiredrill** [comment]
Ah I see, it definitely was a typo 😆 
Also I needed to update my emoji_strategy.json.
Thanks!!
