### ISSUE TITLE
CDN issue

### ISSUE THREAD

**Issue by tylerlong** [Ranks/emojione#463]
I read the [emojione-awesome.css](https://github.com/Ranks/emojione/blob/master/assets/css/emojione-awesome.css) and I found that svg images are hosted by http://cdn.jsdelivr.net/.

Problem is, some of the images are inaccessible, for example: http://cdn.jsdelivr.net/emojione/assets/svg/1f4a5.svg

![image](https://cloud.githubusercontent.com/assets/733544/24759971/c0d9c8f2-1b19-11e7-861b-1cbcaaebbdd3.png)

Most of the hosted images are accessible while some of them are not.  It might be a CDN issue.

**Comment by caseyahenson** [comment]
@tylerlong that shouldn't be happening so I'll look into what's going on there. As a backup, you should be able to uppercase the code point and always retrieve the emoji, both upper and lower case versions are intended to be served from the CDN.

**Comment by tylerlong** [comment]
https://cdn.jsdelivr.net/emojione/assets/svg/1f4a5.svg

This morning I tried again and I could access it. But now I couldn't access it again. 

![image](https://cloud.githubusercontent.com/assets/733544/24796140/69916d48-1bbe-11e7-800d-1042ce57751b.png)

**Comment by kevinranks** [comment]
Hey @tylerlong! 

This week we changed up where we host our assets for the CDN and it looks like some files got left in the dust, or overwritten with their uppercase siblings. Just this morning I went through and rectified the situation.

If you continue to see issues, first make sure your cache is cleared and if the problem persists please let us know. We may have to get jsdelivr to invalidate the cache.

> A question: why isn't there a version number in the url? It should be something like https://cdn.jsdelivr.net/emojione/2.2.7/assets/svg/1f4a5.svg

Back when we launched EmojiOne we opted to serve the _latest_ assets only in order to make sure that everyone using the CDN always has up-to-date artwork. 

With that being said, we'll be launching EmojiOne 3.0 within the next couple weeks. From 3.0 onward we'll have versioned assets 😄 .
