### ISSUE TITLE
:* is not translated with toImage

### ISSUE THREAD

**Issue by N8boy** [Ranks/emojione#491]
The Emoji :* is not translated with the function toImage. Instead I get the :asterisk_sybol: emoji for the *.

With shortnameToImage :* is translated correct.

**Comment by caseyahenson** [comment]
@N8boy this is actually two problems in one here. First, the asterisk symbol shouldn't be replacing and that will be fixed in the 3.0.2 release. Secondly, `unicodeToimage` (used by `toImage` alongside `shortnameToImage`) wasn't previously equipped to handle ASCII which will be fixed in the 3.0.2 release as well. That should be published by tomorrow at the latest.

**Comment by caseyahenson** [comment]
@N8boy this issue is resolved in the 3.0.2 release.
