### ISSUE TITLE
Emoji One does not support skin tone modifier feature

### ISSUE THREAD

**Issue by wp9015362** [Ranks/emojione#69]
Hello,

Emoji One still does not support the skin tone modifier feature.

Could you please add the skin tone modifier feature to Emoji One?

Regards

**Comment by kavirajk** [comment]
+1

**Comment by ck-on** [comment]
I'm writing a patch that will generate the diversity skin tones from the existing svg files.

Should have it done this weekend.

**Comment by metavida** [comment]
Found a sneak peek of Unicode Diversity support via Twitter & wanted to cross-post in case others, like me, went looking for news of pending updates in GitHub first instead of on social media.

![croixstvaaabfhc](https://cloud.githubusercontent.com/assets/1933/10810400/d7791af4-7dbd-11e5-932f-3694b250e770.jpg)

via https://twitter.com/emojione/status/654045338999894016

**Comment by rodrigopolo** [comment]
AFAIK new version will have all diversity, in the mean time:
https://github.com/rodrigopolo/emojione_diversity

**Comment by mikebe11** [comment]
Just to clarify things for new viewers of this issue. We won't be developing the diversity set for the current collection. The upcoming collection (v2) will include support for that. We'll leave this issue up in the meantime for those looking for info or those wanting to take advantage of the patch offered here.

**Comment by mikebe11** [comment]
Took a while but we now support skin tones in V2. Thanks
