### ISSUE TITLE
Why is <span> in ignoredRegexp?

### ISSUE THREAD

**Issue by Synchro** [Ranks/emojione#99]
The first thing I tried to do with Emojione (in PHP) was to convert this shortcode markup to unicode chars:

    <span style="font-size:72px;">:smile:</span>

I was surprised to find it didn't work. I tracked it down to find that the `ignoredRegexp` property makes it not apply to `span`s and some other contexts. I can possibly understand it in object tags, but not spans. Why is that? There are no comments in the code to explain it!

**Comment by kevinranks** [comment]
Hey @Synchro 

The reason for ignoring the <span> is that if ns.sprites is turned on, then we use a <span></span> tag for displaying that emoji image. To prevent breaking the HTML if someone runs the replacement method twice on the same string, we ignore the <span> tags. I agree that this is probably not the best solution and we are currently discussing alternatives. 

Part of the problem is that we like having a copy & paste fallback. For example when the script generates a <span> tag for an emoji sprite, the text inside the span will either be a :shortname: or a native unicode character. That makes it nice when you copy a block of resulting text. When you paste it, it should have either the native unicode or a :shortname:. 

I hope that makes sense. I agree we need to add better commenting, and we are working on that. Any other ideas or contributions to improve the library is welcomed.

**Comment by Synchro** [comment]
OK, that's fair. As a workaround I amended the `ignoredRegexp` before applying the conversion. I'm only ever doing a single conversion from shortcode to unicode (in text that may already contain unicode emoji), so I'm not worried about repeating problems.
